INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOR) VALUES(1,'KSHITIJ_1', 'SOLANKI', 10, 'BLUE');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOR) VALUES(2,'KSHITIJ_2', 'SOLANKI', 11, 'RED');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOR) VALUES(3,'KSHITIJ_3', 'SOLANKI', 12, 'BLACK');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOR) VALUES(4,'KSHITIJ_4', 'SOLANKI', 13, 'YELLOW');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOR) VALUES(5,'KSHITIJ_5', 'SOLANKI', 14, 'WHITE');

INSERT INTO HOBBIES(ID, HOBBY) VALUES (1, 'READING');
INSERT INTO HOBBIES(ID, HOBBY) VALUES (2, 'CHESS');
INSERT INTO HOBBIES(ID, HOBBY) VALUES (3, 'CRICKET');
INSERT INTO HOBBIES(ID, HOBBY) VALUES (4, 'FOOTBALL');
INSERT INTO HOBBIES(ID, HOBBY) VALUES (5, 'TREKKING');

INSERT INTO PERSON_HOBBIES(ID, PERSON_ID, HOBBY_ID) VALUES (1,1,1);
INSERT INTO PERSON_HOBBIES(ID, PERSON_ID, HOBBY_ID) VALUES (2,1,2);
INSERT INTO PERSON_HOBBIES(ID, PERSON_ID, HOBBY_ID) VALUES (3,2,2);
INSERT INTO PERSON_HOBBIES(ID, PERSON_ID, HOBBY_ID) VALUES (4,2,3);
INSERT INTO PERSON_HOBBIES(ID, PERSON_ID, HOBBY_ID) VALUES (5,3,3);
INSERT INTO PERSON_HOBBIES(ID, PERSON_ID, HOBBY_ID) VALUES (6,3,4);
INSERT INTO PERSON_HOBBIES(ID, PERSON_ID, HOBBY_ID) VALUES (7,4,5);
